FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim

# Set the working directory
WORKDIR /app

RUN apt-get update -qq \
      && apt-get install -y \
      build-essential \
      python3-dev \
      ca-certificates \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

# Copy requirements.txt
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Expose port 8000
EXPOSE 8000

# Start the app
CMD [ "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000" ]